world-name: 'gornik'
backpack-capacity: 50000
coal-amount:
  min: 50
  max: 250
coal-price:
  min: 5
  max: 15
event-goal-command: "broadcast piec mikolaja jest pelen!"
event-goal-coal: 1000

database:
  type: 'SQLite'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    username: 'root'
    password: 'password'