name: XL-Mine
version: '${project.version}'
main: me.xlucash.xlmine.MineMain
api-version: '1.19'
commands:
  gornik:
    description: Gornik plugin
    usage: /<command> [reload]
  mikolaj:
    description: Otworz menu eventowe
permissions:
  mine.reload:
      description: Uprawnienie do przeladowania pluginu.
      default: op
depend:
  - PlaceholderAPI